//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icona.Pages {
    
    
    public partial class Communities {
        
        /// <summary>
        /// ToolsContainerControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Icona.Usercontrols.ToolsContainerControl ToolsContainerControl;
        
        /// <summary>
        /// FilterNameTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Icona.Usercontrols.CookiedControls.CookiedTextBoxControl FilterNameTxt;
        
        /// <summary>
        /// AddCommunityBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button AddCommunityBtn;
        
        /// <summary>
        /// CommunitiesUPnl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel CommunitiesUPnl;
        
        /// <summary>
        /// CommunitiesGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView CommunitiesGrid;
        
        /// <summary>
        /// CommunityControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Icona.Usercontrols.CommunityControl CommunityControl;
        
        /// <summary>
        /// WaitControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Icona.Usercontrols.WaitControl WaitControl;
    }
}
