//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icona.Pages {
    
    
    public partial class ModeratedNewsList {
        
        /// <summary>
        /// HeaderLbl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label HeaderLbl;
        
        /// <summary>
        /// ToolsContainerControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Icona.Usercontrols.ToolsContainerControl ToolsContainerControl;
        
        /// <summary>
        /// FilterNameTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Icona.Usercontrols.CookiedControls.CookiedTextBoxControl FilterNameTxt;
        
        /// <summary>
        /// FilterDateFromTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Icona.Usercontrols.CookiedControls.CookiedTextBoxControl FilterDateFromTxt;
        
        /// <summary>
        /// FilterDateTillTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Icona.Usercontrols.CookiedControls.CookiedTextBoxControl FilterDateTillTxt;
        
        /// <summary>
        /// NewsItemsUPnl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel NewsItemsUPnl;
        
        /// <summary>
        /// NewsItemsGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView NewsItemsGrid;
        
        /// <summary>
        /// WaitControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Icona.Usercontrols.WaitControl WaitControl;
    }
}
