//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icona.Pages.Administration {
    
    
    public partial class UsersRegistry {
        
        /// <summary>
        /// ToolsContainerControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Icona.Usercontrols.ToolsContainerControl ToolsContainerControl;
        
        /// <summary>
        /// FilterNameTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Icona.Usercontrols.CookiedControls.CookiedTextBoxControl FilterNameTxt;
        
        /// <summary>
        /// FilterLoginTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Icona.Usercontrols.CookiedControls.CookiedTextBoxControl FilterLoginTxt;
        
        /// <summary>
        /// FilterEmailTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Icona.Usercontrols.CookiedControls.CookiedTextBoxControl FilterEmailTxt;
        
        /// <summary>
        /// FilterRegistrationDateFromTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Icona.Usercontrols.CookiedControls.CookiedTextBoxControl FilterRegistrationDateFromTxt;
        
        /// <summary>
        /// FilterRegistrationDateTillTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Icona.Usercontrols.CookiedControls.CookiedTextBoxControl FilterRegistrationDateTillTxt;
        
        /// <summary>
        /// FilterLastEnterDateFromTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Icona.Usercontrols.CookiedControls.CookiedTextBoxControl FilterLastEnterDateFromTxt;
        
        /// <summary>
        /// FilterLastEnterDateTillTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Icona.Usercontrols.CookiedControls.CookiedTextBoxControl FilterLastEnterDateTillTxt;
        
        /// <summary>
        /// FilterBlockedDdl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Icona.Usercontrols.CookiedControls.CookiedDropDownListControl FilterBlockedDdl;
        
        /// <summary>
        /// AddUserBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button AddUserBtn;
        
        /// <summary>
        /// UsersNumberLbl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label UsersNumberLbl;
        
        /// <summary>
        /// UsersUPnl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UsersUPnl;
        
        /// <summary>
        /// UsersGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView UsersGrid;
        
        /// <summary>
        /// UserProfilesControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Icona.Usercontrols.UserProfileControl UserProfilesControl;
        
        /// <summary>
        /// WaitControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Icona.Usercontrols.WaitControl WaitControl;
    }
}
